"""Add end_date to todos

Revision ID: 2c28c79839b5
Revises: a525e3908341
Create Date: 2025-08-09 01:28:03.330142

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c28c79839b5"
down_revision: Union[str, None] = "a525e3908341"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "todos",
        sa.Column(
            "end_date",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="Task end time",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todos", "end_date")
    # ### end Alembic commands ###
