"""add avatar

Revision ID: 99a2d19f584b
Revises: 88224821fa50
Create Date: 2025-05-08 20:16:33.528747

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99a2d19f584b"
down_revision: Union[str, None] = "88224821fa50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("avatars", sa.Column("avatar", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("avatars", "avatar")
    # ### end Alembic commands ###
