"""fixed surname

Revision ID: a525e3908341
Revises: 99a2d19f584b
Create Date: 2025-05-28 19:52:57.752679

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a525e3908341"
down_revision: Union[str, None] = "99a2d19f584b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Добавляем колонку с серверным значением по умолчанию
    op.add_column(
        "users",
        sa.Column("surname", sa.String(), nullable=False, server_default="Unknown")
    )
    # Если серверный default больше не нужен для новых вставок,
    # его можно сбросить:
    op.alter_column("users", "surname", server_default=None)
    op.drop_column("users", "fullname")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "fullname", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "surname")
    # ### end Alembic commands ###
